# Finance App Service
apiVersion: v1
kind: Service
metadata:
  name: finance-app
  namespace: production
  labels:
    app: finance-app
    team: devops
    env: production
spec:
  type: NodePort
  selector:
    app: finance-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30003
      protocol: TCP
