{{- if or (and (not .Values.postgresql.enabled) .Values.postgres.enabled) (and (not .Values.postgresql.enabled) .Values.externalDatabase) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lims.fullname" . }}-db-secret
  labels:
    {{- include "lims.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgres.enabled }}
  password: {{ .Values.postgres.auth.password | b64enc | quote }}
  {{- else if .Values.externalDatabase }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
