{{- if and (not .Values.postgresql.enabled) .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lims.fullname" . }}-db-secret
  labels:
    {{- include "lims.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
