{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lims.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lims.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "lims.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if and .Values.database.postgresql.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lims.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lims.labels" . | nindent 4 }}
    component: postgresql
spec:
  podSelector:
    matchLabels:
      {{- include "lims.selectorLabels" . | nindent 6 }}
      component: postgresql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow connections from LIMS app pods
    - from:
        - podSelector:
            matchLabels:
              {{- include "lims.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow connections from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9187
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}

---
{{- if and .Values.cache.redis.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lims.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lims.labels" . | nindent 4 }}
    component: redis
spec:
  podSelector:
    matchLabels:
      {{- include "lims.selectorLabels" . | nindent 6 }}
      component: redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow connections from LIMS app pods
    - from:
        - podSelector:
            matchLabels:
              {{- include "lims.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow connections from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9121
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}

---
{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.denyAll }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lims.fullname" . }}-deny-all
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lims.labels" . | nindent 4 }}
    purpose: deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  # This policy denies all traffic by default
  # Other policies will allow specific traffic
{{- end }}