-- Development Seed: 003_seed_samples_and_tests.sql
-- Description: Seed development database with sample data and test results
-- Environment: Development Only
-- Author: DevOps Team

-- Insert sample data
INSERT INTO samples (
    sample_id,
    client_id,
    barcode,
    sample_type,
    test_type,
    priority,
    status,
    volume,
    unit,
    collection_date,
    collection_time,
    collection_location,
    storage_location,
    temperature_requirement,
    special_instructions,
    expected_completion_date,
    notes,
    data_classification,
    retention_category,
    created_by,
    updated_by
) VALUES 
-- Samples for General Hospital Medical Center
(
    'SAMPLE_000001',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_001'),
    'BC000001',
    'blood',
    'genetic',
    'high',
    'completed',
    5.0,
    'mL',
    CURRENT_DATE - INTERVAL '7 days',
    '09:30:00',
    'General Hospital - Room 301',
    'Freezer A1-001',
    '-80°C',
    'Handle with care - cancer genetics study',
    CURRENT_DATE - INTERVAL '2 days',
    'Patient consent obtained for genetic testing',
    'restricted',
    'medical_genetic',
    'system',
    'system'
),
(
    'SAMPLE_000002',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_001'),
    'BC000002',
    'saliva',
    'genetic',
    'normal',
    'in_progress',
    2.0,
    'mL',
    CURRENT_DATE - INTERVAL '5 days',
    '14:15:00',
    'General Hospital - Outpatient Clinic',
    'Freezer A1-002',
    '-20°C',
    'Pharmacogenomics panel requested',
    CURRENT_DATE + INTERVAL '3 days',
    'Patient on multiple medications',
    'restricted',
    'medical_genetic',
    'system',
    'system'
),
(
    'SAMPLE_000003',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_001'),
    'BC000003',
    'tissue',
    'pathology',
    'urgent',
    'pending',
    1.5,
    'cm³',
    CURRENT_DATE - INTERVAL '1 day',
    '11:45:00',
    'General Hospital - OR 5',
    'Pathology Lab - Section B',
    '4°C',
    'Suspected malignancy - rush processing',
    CURRENT_DATE + INTERVAL '1 day',
    'Biopsy sample from surgery',
    'restricted',
    'medical_pathology',
    'system',
    'system'
),
-- Samples for Metropolitan Health System
(
    'SAMPLE_000004',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_002'),
    'BC000004',
    'blood',
    'chemical',
    'normal',
    'completed',
    7.0,
    'mL',
    CURRENT_DATE - INTERVAL '10 days',
    '08:00:00',
    'Metro Health - Lab Collection',
    'Refrigerator B2-001',
    '2-8°C',
    'Comprehensive metabolic panel',
    CURRENT_DATE - INTERVAL '8 days',
    'Fasting sample collected',
    'confidential',
    'medical_clinical',
    'system',
    'system'
),
(
    'SAMPLE_000005',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_002'),
    'BC000005',
    'urine',
    'chemical',
    'normal',
    'in_progress',
    50.0,
    'mL',
    CURRENT_DATE - INTERVAL '3 days',
    '16:30:00',
    'Metro Health - Urology Clinic',
    'Refrigerator B2-002',
    '2-8°C',
    'Drug screening panel',
    CURRENT_DATE + INTERVAL '2 days',
    'Mid-stream clean catch',
    'confidential',
    'medical_clinical',
    'system',
    'system'
),
-- Samples for University Research Institute
(
    'SAMPLE_000006',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_006'),
    'BC000006',
    'blood',
    'genetic',
    'normal',
    'completed',
    10.0,
    'mL',
    CURRENT_DATE - INTERVAL '15 days',
    '10:00:00',
    'University Research Center',
    'Research Freezer R1-001',
    '-80°C',
    'Genome-wide association study',
    CURRENT_DATE - INTERVAL '10 days',
    'Research participant #1001',
    'restricted',
    'research_genetic',
    'system',
    'system'
),
(
    'SAMPLE_000007',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_006'),
    'BC000007',
    'saliva',
    'genetic',
    'normal',
    'in_progress',
    3.0,
    'mL',
    CURRENT_DATE - INTERVAL '8 days',
    '13:45:00',
    'University Research Center',
    'Research Freezer R1-002',
    '-20°C',
    'Epigenetic methylation study',
    CURRENT_DATE + INTERVAL '5 days',
    'Research participant #1002',
    'restricted',
    'research_genetic',
    'system',
    'system'
),
-- Samples for BioPharm Solutions Inc.
(
    'SAMPLE_000008',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_008'),
    'BC000008',
    'blood',
    'biological',
    'high',
    'completed',
    15.0,
    'mL',
    CURRENT_DATE - INTERVAL '12 days',
    '09:15:00',
    'BioPharm Clinical Site',
    'Clinical Freezer C1-001',
    '-80°C',
    'Phase II clinical trial - biomarker analysis',
    CURRENT_DATE - INTERVAL '5 days',
    'Clinical trial participant CT001',
    'restricted',
    'clinical_trial',
    'system',
    'system'
),
(
    'SAMPLE_000009',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_008'),
    'BC000009',
    'tissue',
    'biological',
    'high',
    'in_progress',
    0.5,
    'cm³',
    CURRENT_DATE - INTERVAL '6 days',
    '15:20:00',
    'BioPharm Clinical Site',
    'Clinical Freezer C1-002',
    '-80°C',
    'Immunohistochemistry analysis',
    CURRENT_DATE + INTERVAL '4 days',
    'Clinical trial participant CT002',
    'restricted',
    'clinical_trial',
    'system',
    'system'
),
-- Sample for Individual Patient Services
(
    'SAMPLE_000010',
    (SELECT id FROM clients WHERE client_id = 'CLIENT_010'),
    'BC000010',
    'blood',
    'genetic',
    'normal',
    'pending',
    5.0,
    'mL',
    CURRENT_DATE - INTERVAL '2 days',
    '12:00:00',
    'Individual Testing Center',
    'Freezer I1-001',
    '-20°C',
    'Direct-to-consumer genetic testing',
    CURRENT_DATE + INTERVAL '7 days',
    'Individual patient request',
    'restricted',
    'consumer_genetic',
    'system',
    'system'
) ON CONFLICT (sample_id) DO NOTHING;

-- Insert genetic analysis data
INSERT INTO genetic_analysis (
    sample_id,
    analysis_type,
    genes,
    target_regions,
    sequencing_platform,
    library_prep_method,
    read_depth,
    coverage_threshold,
    quality_score_threshold,
    priority,
    status,
    started_at,
    completed_at,
    analysis_parameters,
    raw_data_location,
    processed_data_location,
    results,
    quality_metrics,
    created_by,
    updated_by
) VALUES 
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'targeted_sequencing',
    ARRAY['BRCA1', 'BRCA2', 'TP53', 'PALB2'],
    ARRAY['chr17:41196312-41277500', 'chr13:32889611-32973805'],
    'Illumina NovaSeq 6000',
    'TruSeq Exome Library Prep',
    150,
    95.0,
    30,
    'high',
    'completed',
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    '{"min_allele_frequency": 0.01, "min_read_depth": 10, "variant_caller": "GATK"}'::jsonb,
    '/data/raw/SAMPLE_000001/',
    '/data/processed/SAMPLE_000001/',
    '{"variants_found": 12, "pathogenic_variants": 2, "vus": 3, "benign_variants": 7}'::jsonb,
    '{"mean_coverage": 145.2, "percent_20x": 98.5, "q30_bases": 95.8}'::jsonb,
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000002'),
    'pharmacogenomics',
    ARRAY['CYP2D6', 'CYP2C19', 'CYP2C9', 'VKORC1'],
    ARRAY['chr22:42522500-42526883', 'chr10:96522463-96612671'],
    'Illumina MiSeq',
    'Amplicon Library Prep',
    200,
    98.0,
    25,
    'normal',
    'running',
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    NULL,
    '{"analysis_type": "pharmacogenomics", "drug_interactions": true}'::jsonb,
    '/data/raw/SAMPLE_000002/',
    '/data/processing/SAMPLE_000002/',
    NULL,
    NULL,
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000006'),
    'whole_exome',
    ARRAY['ALL_EXONS'],
    ARRAY['whole_exome'],
    'Illumina NovaSeq 6000',
    'SureSelect Human All Exon V7',
    100,
    90.0,
    30,
    'normal',
    'completed',
    CURRENT_TIMESTAMP - INTERVAL '12 days',
    CURRENT_TIMESTAMP - INTERVAL '8 days',
    '{"variant_annotation": "VEP", "population_frequency": "gnomAD"}'::jsonb,
    '/data/raw/SAMPLE_000006/',
    '/data/processed/SAMPLE_000006/',
    '{"total_variants": 45678, "coding_variants": 12345, "novel_variants": 456}'::jsonb,
    '{"mean_coverage": 87.3, "percent_20x": 92.1, "q30_bases": 94.2}'::jsonb,
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000008'),
    'rna_sequencing',
    ARRAY['TRANSCRIPTOME'],
    ARRAY['whole_transcriptome'],
    'Illumina NovaSeq 6000',
    'TruSeq Stranded mRNA',
    50,
    85.0,
    25,
    'high',
    'completed',
    CURRENT_TIMESTAMP - INTERVAL '10 days',
    CURRENT_TIMESTAMP - INTERVAL '6 days',
    '{"strandedness": "stranded", "read_length": 150, "paired_end": true}'::jsonb,
    '/data/raw/SAMPLE_000008/',
    '/data/processed/SAMPLE_000008/',
    '{"expressed_genes": 18562, "differentially_expressed": 1234, "novel_transcripts": 89}'::jsonb,
    '{"mapping_rate": 94.7, "duplication_rate": 8.3, "rRNA_rate": 2.1}'::jsonb,
    'system',
    'system'
) ON CONFLICT DO NOTHING;

-- Insert test results
INSERT INTO test_results (
    sample_id,
    test_name,
    test_method,
    result_value,
    result_unit,
    reference_range,
    interpretation,
    is_abnormal,
    confidence_level,
    performed_by,
    reviewed_by,
    equipment_used,
    reagent_lot,
    test_date,
    result_date,
    comments,
    created_by,
    updated_by
) VALUES 
-- Test results for SAMPLE_000001
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'BRCA1 Variant Analysis',
    'Next Generation Sequencing',
    'c.5266dupC (p.Gln1756Profs*74)',
    'variant',
    'No pathogenic variants',
    'Pathogenic',
    TRUE,
    99.5,
    (SELECT id FROM users WHERE username = 'analyst001'),
    (SELECT id FROM users WHERE username = 'analyst002'),
    'Illumina NovaSeq 6000',
    'LOT123456',
    CURRENT_DATE - INTERVAL '3 days',
    CURRENT_DATE - INTERVAL '2 days',
    'Pathogenic frameshift variant in BRCA1 associated with increased breast cancer risk',
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'BRCA2 Variant Analysis',
    'Next Generation Sequencing',
    'No significant variants detected',
    'negative',
    'No pathogenic variants',
    'Negative',
    FALSE,
    98.2,
    (SELECT id FROM users WHERE username = 'analyst001'),
    (SELECT id FROM users WHERE username = 'analyst002'),
    'Illumina NovaSeq 6000',
    'LOT123456',
    CURRENT_DATE - INTERVAL '3 days',
    CURRENT_DATE - INTERVAL '2 days',
    'No pathogenic or likely pathogenic variants identified',
    'system',
    'system'
),
-- Test results for SAMPLE_000004
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000004'),
    'Glucose',
    'Enzymatic Colorimetric',
    '85',
    'mg/dL',
    '70-99',
    'Normal',
    FALSE,
    99.0,
    (SELECT id FROM users WHERE username = 'tech001'),
    (SELECT id FROM users WHERE username = 'analyst003'),
    'Roche Cobas 8000',
    'GLU789012',
    CURRENT_DATE - INTERVAL '9 days',
    CURRENT_DATE - INTERVAL '8 days',
    'Fasting glucose within normal range',
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000004'),
    'Creatinine',
    'Jaffe Kinetic',
    '1.1',
    'mg/dL',
    '0.7-1.3',
    'Normal',
    FALSE,
    98.5,
    (SELECT id FROM users WHERE username = 'tech001'),
    (SELECT id FROM users WHERE username = 'analyst003'),
    'Roche Cobas 8000',
    'CRE345678',
    CURRENT_DATE - INTERVAL '9 days',
    CURRENT_DATE - INTERVAL '8 days',
    'Creatinine within normal range',
    'system',
    'system'
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000004'),
    'Total Cholesterol',
    'Enzymatic Colorimetric',
    '195',
    'mg/dL',
    '<200',
    'Desirable',
    FALSE,
    99.2,
    (SELECT id FROM users WHERE username = 'tech001'),
    (SELECT id FROM users WHERE username = 'analyst003'),
    'Roche Cobas 8000',
    'CHOL901234',
    CURRENT_DATE - INTERVAL '9 days',
    CURRENT_DATE - INTERVAL '8 days',
    'Total cholesterol at desirable level',
    'system',
    'system'
),
-- Test results for SAMPLE_000006
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000006'),
    'Whole Exome Sequencing',
    'Next Generation Sequencing',
    '45678 variants identified',
    'variants',
    'Variable',
    'Research analysis complete',
    FALSE,
    95.0,
    (SELECT id FROM users WHERE username = 'analyst002'),
    (SELECT id FROM users WHERE username = 'analyst001'),
    'Illumina NovaSeq 6000',
    'WES567890',
    CURRENT_DATE - INTERVAL '10 days',
    CURRENT_DATE - INTERVAL '8 days',
    'Comprehensive exome analysis for research study',
    'system',
    'system'
),
-- Test results for SAMPLE_000008
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000008'),
    'RNA Expression Profiling',
    'RNA Sequencing',
    '18562 genes expressed',
    'genes',
    'Variable',
    'Expression analysis complete',
    FALSE,
    92.8,
    (SELECT id FROM users WHERE username = 'analyst001'),
    (SELECT id FROM users WHERE username = 'analyst002'),
    'Illumina NovaSeq 6000',
    'RNA234567',
    CURRENT_DATE - INTERVAL '8 days',
    CURRENT_DATE - INTERVAL '6 days',
    'RNA-seq analysis for biomarker study',
    'system',
    'system'
) ON CONFLICT DO NOTHING;

-- Insert sample tracking events
INSERT INTO sample_tracking_events (
    sample_id,
    event_type,
    event_timestamp,
    location,
    temperature,
    equipment_id,
    performed_by,
    notes,
    metadata
) VALUES 
-- Events for SAMPLE_000001
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'sample_received',
    CURRENT_TIMESTAMP - INTERVAL '7 days',
    'Sample Reception',
    22.5,
    NULL,
    (SELECT id FROM users WHERE username = 'tech001'),
    'Sample received and logged into system',
    '{"barcode_scanned": true, "condition": "good", "volume_verified": true}'::jsonb
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'sample_processed',
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    'Genetics Lab',
    -80.0,
    NULL,
    (SELECT id FROM users WHERE username = 'tech002'),
    'DNA extraction completed',
    '{"extraction_method": "QIAamp", "yield": "150ng/uL", "purity": "1.85"}'::jsonb
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'analysis_started',
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    'Sequencing Lab',
    -20.0,
    NULL,
    (SELECT id FROM users WHERE username = 'tech003'),
    'Sequencing run initiated',
    '{"run_id": "RUN001", "platform": "NovaSeq", "expected_completion": "2024-01-15"}'::jsonb
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'analysis_completed',
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    'Bioinformatics Lab',
    22.0,
    NULL,
    (SELECT id FROM users WHERE username = 'analyst001'),
    'Analysis completed and results reviewed',
    '{"variants_found": 12, "pathogenic_variants": 2, "report_generated": true}'::jsonb
),
-- Events for SAMPLE_000004
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000004'),
    'sample_received',
    CURRENT_TIMESTAMP - INTERVAL '10 days',
    'Sample Reception',
    22.0,
    NULL,
    (SELECT id FROM users WHERE username = 'tech001'),
    'Sample received for chemistry panel',
    '{"barcode_scanned": true, "condition": "good", "fasting_verified": true}'::jsonb
),
(
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000004'),
    'sample_processed',
    CURRENT_TIMESTAMP - INTERVAL '9 days',
    'Chemistry Lab',
    4.0,
    NULL,
    (SELECT id FROM users WHERE username = 'tech002'),
    'Chemistry analysis completed',
    '{"tests_performed": ["glucose", "creatinine", "cholesterol"], "all_tests_passed": true}'::jsonb
);

-- Update system settings
UPDATE system_settings 
SET setting_value = 'true' 
WHERE setting_key = 'seed_data_loaded';

-- Record seed execution
INSERT INTO audit_log (
    table_name,
    record_id,
    action,
    new_values,
    user_id,
    timestamp
) VALUES (
    'samples',
    (SELECT id FROM samples WHERE sample_id = 'SAMPLE_000001'),
    'SEED_DATA_LOADED',
    '{"seed_file": "003_seed_samples_and_tests.sql", "environment": "development", "samples_count": 10, "genetic_analysis_count": 4, "test_results_count": 8}'::jsonb,
    (SELECT id FROM users WHERE username = 'admin'),
    CURRENT_TIMESTAMP
);

COMMIT;