name: CI/CD Pipeline

on:
  push:
    branches: [ main, client-specific ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci
        
    - name: Run tests
      run: |
        npm test
        cd backend && npm test
        
    - name: Run linting
      run: |
        npm run lint
        
    - name: Build application
      run: npm run build

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        npm audit --audit-level moderate
        cd backend && npm audit --audit-level moderate
        
    - name: Check for vulnerabilities
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npx audit-ci --moderate

  docker:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t labscientific-lims:latest .
        
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 3001:3001 labscientific-lims:latest
        sleep 10
        curl -f http://localhost:3001/health || exit 1
        docker stop test-container

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/client-specific'
    
    steps:
    - name: Deploy to staging
      run: echo "Deploy to staging environment"
      
  deploy-production:
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: echo "Deploy to production environment"